prometheus-postgres-exporter:
  serviceMonitor:
    # When set true then use a ServiceMonitor to configure scraping
    enabled: true
    # Set the namespace the ServiceMonitor should be deployed
    namespace: monitoring

    # Set how frequently Prometheus should scrape
    interval: 30s
    # Set path to cloudwatch-exporter telemtery-path
    telemetryPath: /metrics
    # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
    labels:
      Release: prom
    # Set timeout for scrape
    timeout: 10s
    # Set of labels to transfer from the Kubernetes Service onto the target
    # targetLabels: []
    # MetricRelabelConfigs to apply to samples before ingestion
    # metricRelabelings: []
    # Set relabel_configs as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
    # relabelings: []
